// Code generated by mockery v2.40.1. DO NOT EDIT.

package mocks

import (
	http "net/http"

	dto "github.com/AlgorithmChopda/ecommerce-for-sneakers-API-in-go/internal/pkg/dto"

	mock "github.com/stretchr/testify/mock"
)

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

// GetUserList provides a mock function with given fields: r
func (_m *Service) GetUserList(r *http.Request) ([]dto.UserResponseObject, error) {
	ret := _m.Called(r)

	if len(ret) == 0 {
		panic("no return value specified for GetUserList")
	}

	var r0 []dto.UserResponseObject
	var r1 error
	if rf, ok := ret.Get(0).(func(*http.Request) ([]dto.UserResponseObject, error)); ok {
		return rf(r)
	}
	if rf, ok := ret.Get(0).(func(*http.Request) []dto.UserResponseObject); ok {
		r0 = rf(r)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]dto.UserResponseObject)
		}
	}

	if rf, ok := ret.Get(1).(func(*http.Request) error); ok {
		r1 = rf(r)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUserProfile provides a mock function with given fields: userId
func (_m *Service) GetUserProfile(userId int) (dto.UserResponseObject, error) {
	ret := _m.Called(userId)

	if len(ret) == 0 {
		panic("no return value specified for GetUserProfile")
	}

	var r0 dto.UserResponseObject
	var r1 error
	if rf, ok := ret.Get(0).(func(int) (dto.UserResponseObject, error)); ok {
		return rf(userId)
	}
	if rf, ok := ret.Get(0).(func(int) dto.UserResponseObject); ok {
		r0 = rf(userId)
	} else {
		r0 = ret.Get(0).(dto.UserResponseObject)
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(userId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// LoginUser provides a mock function with given fields: email, passsword
func (_m *Service) LoginUser(email string, passsword string) (string, error) {
	ret := _m.Called(email, passsword)

	if len(ret) == 0 {
		panic("no return value specified for LoginUser")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) (string, error)); ok {
		return rf(email, passsword)
	}
	if rf, ok := ret.Get(0).(func(string, string) string); ok {
		r0 = rf(email, passsword)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(email, passsword)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RegisterUser provides a mock function with given fields: userInfo, userRole
func (_m *Service) RegisterUser(userInfo dto.RegisterUserRequest, userRole string) (dto.UserRegisterResponseObject, error) {
	ret := _m.Called(userInfo, userRole)

	if len(ret) == 0 {
		panic("no return value specified for RegisterUser")
	}

	var r0 dto.UserRegisterResponseObject
	var r1 error
	if rf, ok := ret.Get(0).(func(dto.RegisterUserRequest, string) (dto.UserRegisterResponseObject, error)); ok {
		return rf(userInfo, userRole)
	}
	if rf, ok := ret.Get(0).(func(dto.RegisterUserRequest, string) dto.UserRegisterResponseObject); ok {
		r0 = rf(userInfo, userRole)
	} else {
		r0 = ret.Get(0).(dto.UserRegisterResponseObject)
	}

	if rf, ok := ret.Get(1).(func(dto.RegisterUserRequest, string) error); ok {
		r1 = rf(userInfo, userRole)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewService creates a new instance of Service. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewService(t interface {
	mock.TestingT
	Cleanup(func())
}) *Service {
	mock := &Service{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
