// Code generated by mockery v2.40.1. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// BrandRepository is an autogenerated mock type for the BrandRepository type
type BrandRepository struct {
	mock.Mock
}

// GetBrandId provides a mock function with given fields: brand
func (_m *BrandRepository) GetBrandId(brand string) (int, error) {
	ret := _m.Called(brand)

	if len(ret) == 0 {
		panic("no return value specified for GetBrandId")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (int, error)); ok {
		return rf(brand)
	}
	if rf, ok := ret.Get(0).(func(string) int); ok {
		r0 = rf(brand)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(brand)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewBrandRepository creates a new instance of BrandRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBrandRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *BrandRepository {
	mock := &BrandRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
